### ISSUE TITLE
Highlight settings based on broswer alt image support

### ISSUE THREAD

**Issue by aduke** [jamietre/ImageMapster#110]
Is it possible to change opacity for a area depending on whether the browser supports altimage?  I wan't to disable the highlight of an area if altimage is not supported.

**Comment by techfg** [comment]
Hello @aduke -

We never heard back from you regarding this so I'm going to close this out.

If you have any further questions, please see the options listed on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.  If you feel you have encountered a bug in IM, please feel free to submit a new issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
