### ISSUE TITLE
Choosing fill color for the areas

### ISSUE THREAD

**Issue by chuchor1** [jamietre/ImageMapster#117]
Hey there guys im new to imagemap and jquery. I found it to be very nicely built, right now im working on a project wich lets the user click an area of the human body and also the color that the area wil be fill with,  basically it will be two colors re and green, is there a way  to combine the plugin colorpicker to do this or is there an easier way.  
Heres where i am at http://jsfiddle.net/chucho/v7Kdn/4/, only the right image is maped.

**Comment by techfg** [comment]
Hello @chuchor1  -

Thank you for your inquiry, apologies for the delayed reply.

IM doesn't currently support a feature that would allow the user to "decide/choose" which color to apply to a selected area.  With that said, it is something you could implement via the [onClick](http://www.outsharked.com/imagemapster/default.aspx?docs.html#onclick) option of IM.

If you'd like assistance on how to achieve this, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for more details on how to obtain general assistance on IM.
