### ISSUE TITLE
resize to fill height OR width

### ISSUE THREAD

**Issue by petergus** [jamietre/ImageMapster#123]
Im trying to make an image map image fill the container window (so if the window is narrow part of the image will just be cut off on the side, so there is no white space under).

basing my attempts on the resize fiddle at http://jsfiddle.net/jQG48/ 
i have noticed the `>` selector in `imgWidth/maxWidth>imgHeight/maxHeight` can be reversed to use either height or width stretching.

so my jquery is not so good, anyone have some tips how to make it fill to whichever is smaller so it can fill the white space?

**Comment by techfg** [comment]
Basic auto-resize support as described in #359 was added in #360.
