### ISSUE TITLE
Writing Text into a hotspot area

### ISSUE THREAD

**Issue by hussainhaideri** [jamietre/ImageMapster#128]
Hi,
       Is it possible to write any text on the polygon hotspot area of the map at runtime ? The text should fit into the hotspot area and should scale up or down with the map when zoomed. 

Any suggestions / ideas would be highly appreciated. 

Thanks,

**Comment by techfg** [comment]
Hello @hussainhaideri -

Thank you for your inquiry, apologies for the delayed reply!

Beyond tooltips, IM doesn't provide any method of writing text in to a hotspot.  That said, through the use of the various events that IM exposes (e.g. onClick, onMouseover, etc.) you can likely achieve what you are after with your own custom solution.  See the `Events` section of the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html) for more information.

If you'd like to see this feature added to IM, please open a new issue per our [Feature Request](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines referencing this issue.  PRs are welcome!
