### ISSUE TITLE
Cant open modal window from href

### ISSUE THREAD

**Issue by frenchy74** [jamietre/ImageMapster#131]
Hi Jamie

I'm having trouble getting the href to open a modal link in Joomla. See

http://staging.sohovillage.com.au/index.php/adlephi-level-1

I've contacted the script for the pop-up and I got this message

There appears to be a conflict with the imagemapster script you are using, which also attaches an onclick handler to the area element.

I've added a fiddle here with the code here

http://jsfiddle.net/frenchy74/dGJcM/1/

Any help would be much appreciated

**Comment by techfg** [comment]
Hello @frenchy74 -

We never heard back from you so we're going to close this issue.

If you have any further questions, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for ways to receive support on ImageMapster.  If you believe you have identified a bug, please open a new issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
