### ISSUE TITLE
zooming by centerized view image map

### ISSUE THREAD

**Issue by sajalx** [jamietre/ImageMapster#132]
respected sir/mam,
  i would like to zoom a image in by centralized zooming in your project Image Map.
In your Image Map project when i am zooming the image that will zoomed from a corner of a site, is that possible for zooming the image by its center means it will zoom from center.
please contact me regarding the solving of that issue what i have mention.

my no:(91)9903076025
email Id: industryjobx@gmail.com

**Comment by UksusoFF** [comment]
Any news about this issue?
http://blog.outsharked.com/2011/10/another-new-imagemapster-feature-area.html

**Comment by techfg** [comment]
Hello @sajalx/@UksusoFF -

Thank you for your questions, apologies for the delayed reply.

As @jamietre indicated, there is no support for zooming in IM.  This was something that was being worked on a while back but unfortunately wasn't able to be completed so was never officially added.

If this is something you'd like to see added, please feel free to submit a feature request per our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.  Once submitted, we can discuss as a community regarding scope/spec and determine if there's enough interest for someone to implement and submit a PR.
