### ISSUE TITLE
Marker for Areas - possible? 

### ISSUE THREAD

**Issue by Domtaholic** [jamietre/ImageMapster#139]
Hey,

is der a way i can bind markers to the areas? I got a map of a land, on it some Buildings and real areas, now i got buildings in the areas and have to attach markers to these buildings, but still they(the areas and the buildings) can be highlighted. The Image should be the better explaintation ;)

Is there a way to get such an Image to the desired areas? 

Thanks for any help
![karte_new](https://f.cloud.github.com/assets/3584433/589641/43e6afa2-c9c6-11e2-99fd-3fd61f8b9f5d.png)

**Comment by techfg** [comment]
Hello @Domtaholic -

It appears that @jamietre was able to help you find a solution for you question/issue so I'm going to close this issue.

Regarding your question about adding markers, there are some other libraries out there that include this behavior but if you'd like to see this added to IM, please feel free to submit a new issue per our [Feature Request](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines referencing this issue.  PRs are welcome!
