### ISSUE TITLE
Uncaught TypeError with mouseoutDelay: -1

### ISSUE THREAD

**Issue by martbean** [jamietre/ImageMapster#142]
Hi,

I have mouseoutDelay set to -1 so the highlight effect stays until you mouseover another area and it's working but giving this error:

Uncaught TypeError: Cannot call method 'then' of undefined in line 2780

Chrome 27, Firefox 21 and IE9 all give variations of this error. Here's a jsfiddle:

http://jsfiddle.net/QReeg/

Any ideas?
Thanks,
Martin.

**Comment by techfg** [comment]
Closing this after confirming it was fixed/resolved in 1.2.13.

FYI - The change made to resolve this led to #364 which will be fixed in 1.5.2.
