### ISSUE TITLE
Remove cursor / multiple map keys

### ISSUE THREAD

**Issue by rapha2** [jamietre/ImageMapster#151]
Hi everyone,
is there any way to remove the hand-cursor of certain areas so that they are completely static?
And my second question is, weather it is possible to create multiple map keys like so:

```
mapKey: 'class',
areas : [
{key : 'testclass',fillColor: '7DA83F',fillOpacity : 0.9}
],
mapKey: 'id',
areas : [
{key : 'testid',fillColor: '7DA83F',fillOpacity : 0.9}
]
```

Thanks, I appreciate your help!

Rapha

**Comment by techfg** [comment]
Hi @rapha2 -

It appears that your original questions were answered, and you opened #159 for your most recent question so closing this and will address your second question there.
