### ISSUE TITLE
Image Map in a separate file

### ISSUE THREAD

**Issue by snehaver** [jamietre/ImageMapster#155]
Hello, 

I am trying to to modify image map, according to the coordinates stored in a data based. Want to know if its possible to save image map in a separate file and updating that file. 

Any other way to do the same...

**Comment by techfg** [comment]
Hello @snehaver -

Thank you for your inquiry, apologies for the delayed reply!

IM doesn't provide any method of saving an image although this can be accomplished outside of IM.  There have been a few requests for adding a feature to IM to support saving the image/canvas so if this is something that you'd like to see added, please feel free to submit a new issue per our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.  PRs are welcome!
