### ISSUE TITLE
Any way to rotate an image with mapster bound?

### ISSUE THREAD

**Issue by whutchis23** [jamietre/ImageMapster#160]
Just so - I need to be able to rotate an image while Mapster is bound to the image/imagemap.   Rotation via CSS works great on "bare" images, but once Mapster creates the canvas for rendering, no rotation or positioning seems to work.   Also, an image that is rotated is returned to angle(0deg) once Mapster connects to the image.   Any hints?

**Comment by techfg** [comment]
Hello @whutchis23 -

Based on your last comment, it appears that you found a solution to your question.

If that is not the case, as @jamietre mentioned, adding a "rotation" feature to IM is definitely possible, although not necessarily trivial.  If you'd like to officially request this feature, please feel free to submit a new issue per our [Feature Request](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines and reference this issue.
