### ISSUE TITLE
Tooltip blocks altimages

### ISSUE THREAD

**Issue by cretace** [jamietre/ImageMapster#162]
I have moved the tooltips to be centred over the image map area and I have altimages specified.
So when I rollover the area everything works, but when I am rolled over the tooltip that pops up, the altimages revert to default image.

How can I pass the hover status through the tooltip ?

**Comment by techfg** [comment]
Hello @cretace -

We never heard back from you regarding this so I'm going to close out this issue.

If you would like further assistance, please open a new issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate.
