### ISSUE TITLE
jquery imagemapster set_options method working randomly

### ISSUE THREAD

**Issue by sachinkulkarni99** [jamietre/ImageMapster#163]
I am having following code block in my js file.

jQuery('#28,#29,#210,#211').mapster('deselect');  // deselect all area first
jQuery('.map').mapster('set_options', initialOptions);   // change color of area
jQuery('#28,#29,#210,#211').mapster('select');      // select area after changing color

where initialOptions is

{"areas":[{"key":"28","fillColor":"FF0000"},{"key":"29","fillColor":"FF0000"},{"key":"210","fillColor":"FF0000"},{"key":"211","fillColor":"FF0000"}]}

This code block works fine when called on window.load event but when i change image dynamically and then calls this code it works sometimes randomly ....

Note: i have already cached all the images before assigning them dynamically.

I have added console.log in jquery.imagemapste.js and found that  merge_options method is not gets called randomly.

Please help me to resolve this issue.

**Comment by techfg** [comment]
Hello @sachinkulkarni99 -

We never heard back from you regarding this so I'm going to close out this issue.

If you would like further assistance, please open a new issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate.
