### ISSUE TITLE
are altImage options obsolete?

### ISSUE THREAD

**Issue by szepeviktor** [jamietre/ImageMapster#166]
```
    altImageFill: true,
    altImageStroke: false,
    altImageOpacity: 0.7
```

I cannot find them in the source.
Please help.

**Comment by techfg** [comment]
Hello @szepeviktor -

Thank you for your inquiry, apologies for the delayed reply!

`altImageOpacity` is a valid and supported configuration option, however `altImageFill` and `altImageStroke` are not (don't believe they ever were although possibly at some point in a very early version).

As you correctly identified in follow-up, `fill`, `fillColor/ColorMask/Opacity`, `stroke` and  `strokeColor/Opacity/Width` are the correct options to control those properties.

If you are having any issues with these working as expected, please feel free to submit a new issue per our [Bug Report](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.

**Comment by szepeviktor** [comment]
Hello @techfg!
A decade ago there was another viktor :)

**Comment by techfg** [comment]
Hi @szepeviktor -

lol, thanks for the update! I'll go ahead and close this ticket.

**Comment by rafamorac** [comment]
Can someone pleeeaase remove me ? Tyvm

**Comment by szepeviktor** [comment]
@rafamorac You have this repo on your watch: https://github.com/jamietre/ImageMapster/watchers
