### ISSUE TITLE
using imagemapster with mailto: link

### ISSUE THREAD

**Issue by prman** [jamietre/ImageMapster#168]
I've created a simple imagemapster set up successfully on this page: http://drumprofessor.net/testimonials/testimonials.html 

I have the image maps set to open new windows (or tabs) upon clicking. 

But one of the links is a mailto: target - I'm wondering how to get that link to open the users default email client. 

It works fine on this page:
http://drumprofessor.net/contact/contact.html
But there I have "clickNavigate: true"

For the testimonials page, I had to remove "clickNavigate: true" in order to add the onClick function to disable the default behavior and open the link in a new window. But I need an exception for the "mailto" link. Any tips?

Great script by the way. Thanks - from Peter

**Comment by techfg** [comment]
Full support for href & target handling has been added in #354
