### ISSUE TITLE
Dynamically Add Area

### ISSUE THREAD

**Issue by N8DNX** [jamietre/ImageMapster#171]
I'm new to ImageMapster, but so far it looks like it's really going to be helpful.

One thing I can't figure out is if there's a way to dynamically add a new area to the image map and have ImageMapster detect it. The way I have it now is that each new area gets added using a jQuery "prepend" to the image map. To get ImageMapster to manage that, I have been essentially killing and restarting it each time so it will re-read the image map. That seems to cause memory and performance issues with the browser if the user does this too often. 

I've tried to figure out if there's any way to use rebind or any other documented feature to do this but not finding what I need. Is it possible using the current version or am I doing it the only way available at this point.

Thanks.

**Comment by techfg** [comment]
Hello @N8DNX -

Thank you for your inquiry, apologies for the delayed reply.

As @stacysimpson indicates, `unbind` and then initializing mapster is the only supported approach for detecting dynamic areas, etc.  Regarding resource utilization, there have been some recent bugs fixed along this line so I would encourage you to try the latest version (currently v1.5.1) and see if you still see those issues.

If you do, please feel free to open a new issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate further.
