### ISSUE TITLE
Map overlaps with header slider

### ISSUE THREAD

**Issue by pandavegas** [jamietre/ImageMapster#175]
Hello Jamie,

Thanks for creating such wonderful plug in. I have used for almost a year now and never experienced any issues.

I am now noticing that the image pop-ups are overlapping with the slider used as page header. How can this be fixed? 
![screen](https://f.cloud.github.com/assets/6266616/1811995/201078fe-6e69-11e3-958c-bf2891b045f4.jpg)

Also I haven't upgraded the plug in to the latest version. I actually didn't find any instructions for non-coders that I can follow. Do you know where I can find step by step instructions? I do have FTP access to my site, but I am not a developer. Just work with wordpress admin..

I thank you in advance for your help.

Ximena

**Comment by techfg** [comment]
Hello @pandavegas  -

Thank you for your inquiry and apologies for the delayed reply!  I echo your sentiments, @jamietre did a fantastic job with ImageMapster :)

Regarding your particular issue, unfortunately the problem you are encountering seems to be occurring outside of ImageMapster and I do not believe that ImageMapster is causing it.  IM doesn't have any functionality for popups so I'm guessing that there is something in your WP site (possibly another plugin) that is opening the popup and that would be where you would need to focus regarding support for this.

I apologize we can't be of any additional assistance on this!
