### ISSUE TITLE
Tooltips from <area> title content

### ISSUE THREAD

**Issue by NKarasek** [jamietre/ImageMapster#177]
I recently converted a website with MANY "areas" in various imagemaps each using the usual browser tooltip mechanism of tooltip content within the "title" keyword (title="some tooltip".)  Setting up IM's area : [{...}] with a key for each "area" in order to use tooltips was a bit of a pain - not difficult, of course, just very time consuming.  Idea!!  Let IM access the title keyword's info directly - aha.  So - with a new config variable toolTipFromTitle = true/false, and 15 lines of code added to jquery.imagemapster.js, IM now provides this functionality.  NO keys are required within the "area" tags, and NO  area : [{...]} is required in the startup config section.  If ALL you are doing is highlighting a map area and displaying a tooltip for that area - this solution could be for you.  Caveat - this has NOT been tested in all scenarios - even Jamie has trouble getting testing to be exhaustively complete :-)  Feedback/questions/comments solicited.

**Comment by techfg** [comment]
ImageMapster now supports tooltip functions allowing you to accomplish what you are after.  You can use a function to retrieve/calculate the tooltip meaning in your case, you would no longer have to configure a specific `area` with a corresponding tooltip.  See #347 for details and the [tooltip example](https://github.com/jamietre/ImageMapster/blob/master/examples/tooltips.html#L170)
