### ISSUE TITLE
Tooltip visible with mouseover and stay visible by click.

### ISSUE THREAD

**Issue by elkajetan** [jamietre/ImageMapster#181]
Hello, I am new at the forum. Unfortunately, I'm also fairly a newbie.At the beginning I wanted to apologize for my english.
So, I would like to make my tooltip be visible with mouseover and invisible with mouseout. But I also want the tooltip stay visible when I click on target. When tooltip stay visible by clicking, other tooltips shouldn't be visible, even with mouseover. When I close the tooltip by clicking outside the tooltip other tooltips should be visible on mouseover and stay visible by clicking on target (just like the first one).

Here's the part of my code:

```
<div id="field">
            <img src="images/map.jpg" width="960" height="840" alt="map" usemap="#map1">
            <map id="map1" name="map1">
                <area shape="rect" id="1" alt="1" title="" coords="380,4,676,278" href="#"/>
                <area shape="rect" id="2" alt="2" title="" coords="7,281,376,503" href="#"/>
                <area shape="rect" id="3" alt="3" title="" coords="384,286,678,498" href="#"/>
        </div>


<script language="javascript">
        $(document).ready(function()
            {
                $('img[usemap]').mapster({
                fillColor: 'ffffff',
                fillOpacity: 1,
                clickNavigate: true,
                isSelectable: false,
                isDeselectable: false,
                staticState: true,
                mapKey: 'id',
                listKey: 'id',
                showToolTip: true,
                toolTipClose: 'area-click',

                areas:[
        {key: "1", toolTip: $('<div class="tooltip"><img src="images/img1.jpg" alt="img1" /></div>')},
        {key: "2", toolTip: $('<div class="tooltip"><img src="images/img2.jpg" alt="img2" /></div>')},
    {key: "3", toolTip: $('<div class="tooltip"><img src="images/img3.jpg" alt="img3" /></div>')},    
    ],  
      });
});
</script>

```

Is this even possible to do? Please help.

**Comment by techfg** [comment]
Hello @elkajetan -

Thank you for your inquiry, apologies on the delayed reply!

Unfortunately, there is no "stock" way to achieve what you are trying to do with IM.  However, you can implement a custom solution to achieve this.

To start with, you'd want to set `showToolTip = false` so display IM from automatically showing tooltips.  Then, you'd want to implement handlers for `onClick`, `onMouseover`, `onMouseout` (see the **Events** section in the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html) for info on these).  Within these methods, you can implement custom logic to track state and show/hide tooltips based on your requirements using the [tooltip](http://www.outsharked.com/imagemapster/default.aspx?docs.html#tooltip) API.

I hope this is helpful.  If you have any further questions, please refer to our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for resources on the best places to obtain help on general usage of ImageMapster.
