### ISSUE TITLE
Opening PrettyPhoto/Lightbox with ClickNavigate

### ISSUE THREAD

**Issue by reddo123** [jamietre/ImageMapster#183]
Hi,

Is is possible to open a Prettyphoto or other lightbox alternative when clicking on an area?

Here's what I use below, and is what is required of PrettyPhoto. Have tested without imagemapster and it works.
    <area shape="circle" id="map1" coords="306,373,144" href="http://www.pano-ad.com.au/panos/kstreet/tour.html?iframe=true&width=100%&height=100%" rel="prettyPhoto[image_map]"  /> 

and js

```
<script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
            $("area[rel^='prettyPhoto']").prettyPhoto({
            slideshow: false,
            theme: 'pp_default',
        });
        });
        </script>
```

Any way I can get imagemapster to read the rel tag?
Thanks for any help

**Comment by techfg** [comment]
Hello @reddo123 -

Thank you for the inquiry, apologies for the delayed reply!

I'm not familiar with how prettyPhoto works but what you want to achieve is possible.  If prettyPhoto automatically opens on click event or something similar, it should "just work."  The only reason I would think it might not is that IM does call `preventDefault` which might impact behavior.  If that's the case or if you need to programmatically trigger prettyPhoto, you can add an onClick handler to your IM configuration and within there, call prettyPhoto.  Please see [onClick](http://www.outsharked.com/imagemapster/default.aspx?docs.html#onclick) in the docs for more info.

Hope this helps!  As an aside, for future reference, please follow the guidance described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for general usage questions.
