### ISSUE TITLE
ImageMapster and Thickbox

### ISSUE THREAD

**Issue by csbrou** [jamietre/ImageMapster#186]
First. Thanks so much. This is a great plugin. I have it working just the way I want it to except I need my links to open another page on the site using thickbox. It requires an href with a class to open the thickbox. I have it working on the site outside of imageMapster but when I click on a link it acts like its going to open thickbox then it stops and opens the page normally. I've have read a number of the posts on here but I can't find what I need.
Here is the page. http://staging.ambitionpark.com/availability/
(The ONLY link set up for thickbox is Building 1 Suite A on the very BOTTOM RIGHT corner.)

Script is below. I would really appreciate any help you can give me.

$(document).ready(function(){
$('#centralmap').mapster({
        mapKey: 'status',
        areas:[{
            key: 'sold', 
            selected: true, 
            isSelectable: false,
            staticState:true,
            fillOpacity:.5,
            render_highlight: { 
                altImage:'http://staging.ambitionpark.com/wp-content/themes/agency-pro/images/site-units-sold.png',
                fill: true,
                fillColor: '1F699F',  
                fillOpacity: 1,
                },
            render_select: {
                altImage:'http://staging.ambitionpark.com/wp-content/themes/agency-pro/images/site-units-sold.png',
                altImageOpacity:.8,
                }
        }],
        clickNavigate: true,
                isDeselectable:false,
        fillOpacity:1,
        render_select: {
            altImage:'http://staging.ambitionpark.com/wp-content/themes/agency-pro/images/site-units-available.png',
            altImageOpacity:1,
            },
        altImage: 'http://staging.ambitionpark.com/wp-content/themes/agency-pro/images/site-units-hover.png',
        altImageOpacity: 1,
    })
    .mapster('set', true, '4A,4B,4c,4D,4E,4F,4G,4H,4I,3G,3F,3E,3D,3C,3B,3A,2A,2b,2C,2D,2E,2F,2G,2H,2I,2J,2K,1K,1J,1I,1H,1G,1F,1E,1D,1C,1B,1A');
});

**Comment by techfg** [comment]
Hello @csbrou -

Thank you for your inquiry and apologies for the delayed reply!

Based on your comments, it sounds like you have resolved your issue so I'm going to close this.  Before doing so though and just FYI, I think a simpler solution would have been to simply set `clickNavigate` to false when initiatializing mapster (this is the default value so you must have been setting it to `true`).  By leaving it false, IM will not try to navigate to the href identified in the area element.
