### ISSUE TITLE
Odd behavior when resizing imagemaps with altImages

### ISSUE THREAD

**Issue by boxboy** [jamietre/ImageMapster#192]
You have a great plugin here and it works very well. I have run into an issue that I think is a bug. I used the code laid out in your demo for dynamically resizing the image map when the window is resized: http://jsfiddle.net/jamietre/jQG48/
I just modified one of the lines of code to: 
$('img').mapster({
    mapKey: 'state',
    altImage: 'https://github.com/jamietre/ImageMapster/raw/master/examples/images/usa_map_720_alt_5.jpg'
});
This works fine with jquery-1.6.2, but with jquery-1.10+ after resizing the image map does get updated but the altImage is also displayed below the image map. So that page effectively becomes twice the height of the resized image.

**Comment by derrickxiang** [comment]
I run into the same issue recently and can't figure out a way, have you found a solution?

**Comment by boxboy** [comment]
I think I just stuck with jquery-1.6.2

**Comment by techfg** [comment]
This issue was resolved in #360 as described in #357.
