### ISSUE TITLE
Tooltip near mouse pointer

### ISSUE THREAD

**Issue by akalongman** [jamietre/ImageMapster#194]
Possible set tooltip position at near mouse pointer?

**Comment by techfg** [comment]
Hello @akalongman  -

Did the info @jamietre provided you with help to resolve your question?

**Comment by akalongman** [comment]
@techfg 7 years is a long time, I dont remember 😂

**Comment by techfg** [comment]
lol, it was only 6 years and 10 months! 😃 

Ok, I'm going to close this one out, thanks for getting back to me!
