### ISSUE TITLE
fill image except area

### ISSUE THREAD

**Issue by omkelderman** [jamietre/ImageMapster#197]
So far i havent found this feature in the docs.
I like ImageMapster a lot. It does great things, but this would be awesome. For example highlighting a part of the image, so if you hover over an image-area, the whole image get dark except for that area.
(maybe an extra option `fillType: inner/outer` or something?)

**Comment by techfg** [comment]
Hello @omkelderman -

I'm glad the examples @jamietre helped provide you with a solution on this.  Agreed that there could be a more streamlined way to do this.  

If this is something you are still interested in seeing IM support, please feel free to submit [Feature Request](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) per our guidelines and reference this issue as a starting point.  Additionally, we'd be happy to review a PR if you or anyone else would like to submit.
