### ISSUE TITLE
Capture data using unselect/select

### ISSUE THREAD

**Issue by wsocket** [jamietre/ImageMapster#204]
I'm trying to use the "unselected or selected" example, it works great but I need a way to capture the results.  For example, if I have 4 areas
and area 1 turns green with one click (or red with double-click) can I store values for green/red for this area?

**Comment by techfg** [comment]
Hello @wsocket -

Thank you for your inquiry, apologies for the delayed reply!

IM provides an the [get](http://www.outsharked.com/imagemapster/default.aspx?docs.html#get) API to retrieve the list of currently "selected" areas.  I'm not exactly sure how you are using red/green but this sounds like possibly some additional state regarding the area.  IM doesn't provide a way to "store" this specifically but you do have some options.  One way would be to set a data attribute on the area.  Then, as needed, you could retrieve the selected areas via `get` API and inspect the value of the data attribute for their red/green status.

Hoping this helps.  If you have any further questions, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for information on how to best obtain assistance for general support/usage questions on IM.
