### ISSUE TITLE
AngularJS Support.

### ISSUE THREAD

**Issue by Karttin** [jamietre/ImageMapster#207]
Hello,

I love your component. It works perfectly.

Is there any possibility to have angularJS support?

Kind Regards
Kay

**Comment by MB34** [comment]
I'd love to see this as well. I may do my own conversion.

**Comment by techfg** [comment]
As of v1.3.0, imagemapster has full UMD support and can be installed via [npm](https://www.npmjs.com/package/imagemapster).
