### ISSUE TITLE
'Can't access data until binding complete'

### ISSUE THREAD

**Issue by HelenMamalaki** [jamietre/ImageMapster#208]
Problem: I'm just trying to understand why the line $('#bodyMap').mapster('get')); throws 'Can't access data until binding complete' I looked at the response to a similar question https://github.com/jamietre/ImageMapster/issues/96 but I don't understand how to use "onConfigured" solve my problem. Please see a snippet of my code here, http://jsfiddle.net/59KP5/2/ basically i want the user to be able to select multiple areas, and once they are done I want to retrieve a list of all the areas selected.

Context: I want to do this so that I can keep track of the state of the diagram after the user clicks done, either so that I can later store the selected areas as a JSON object and because I clear and reuse the same map for different scenarios, and if the user goes back to view their selections for a given scenario I want to be able to reload their selections for that scenario. What is the easiest way of doing this? Thank you.

**Comment by justingish** [comment]
I know this issue is super old, but I ran into the same problem and found the answer.  It's a simple typo in the jQuery selector. 

If you look at the fiddle provided, they are creating the mapster object using $("#bodyImg").mapster(), but when you click the done button they are trying to access the data using $('bodyMap').mapster('get').  Notice the jQuery selectors are different.

If you fix that typo in the jQuery selector, the fiddle works just fine.

**Comment by jamietre** [comment]
I'd welcome a pull request - I just am not maintaining this any more.

**Comment by justingish** [comment]
There's no bug. This issue should just be closed. It was a mistake that the OP made.  Sorry if that wasn't clear.

It's pretty cool that you built this library so many years ago and it is still useful to so many people even after you've stopped maintaining it.  Good work!

**Comment by techfg** [comment]
Hello @HelenMamalaki -

Thank you for your inquiry, apologies in the delayed reply.

As @justingish correctly points out, the bug/issue here is not with IM but rather with the jsFiddle you referenced.  Fixing the javascript in the fiddle corrects the issue.

Thanks for the assist @justingish!
