### ISSUE TITLE
open hrefwith click on a area 

### ISSUE THREAD

**Issue by ghost** [jamietre/ImageMapster#210]
hi i use this 
i need when Mouse goes on a area, the area be hilight Exactly like the demo:
http://www.outsharked.com/imagemapster/examples/usa.html

but i need when you one click on it:  go to the href in area
Sorry for my poor English
like this: (but this demo's areas href is #)
http://davidlynch.org/projects/maphilight/docs/demo_world.html#

**Comment by techfg** [comment]
By default, imagemapster will not navigate to href in area.  Your solution to set clickNavigate to true in options is the correct solution.
