### ISSUE TITLE
Image map sometimes displays as thumbnail?

### ISSUE THREAD

**Issue by beccalm** [jamietre/ImageMapster#213]
I'm using the ImageMapper Wordpress plugin on my site, which is based on ImageMapster, so I thought I'd come here for help.

I have an image map on my site, and sometimes when you open the page the map displays normally, at its full width and height, and sometimes it displays at 100x100 px. I tried using the resizing script here http://jsfiddle.net/jamietre/jQG48/ to fix it, but that broke my hotspots and didn't fix the random thumbnail sizing.

Any ideas what might be happening?

**Comment by techfg** [comment]
Appears this issue was resolved, closing.
