### ISSUE TITLE
Is there a way to 

### ISSUE THREAD

**Issue by NhatL** [jamietre/ImageMapster#214]
This is what I have right now:

$(document).ready(function () {
       var image = $('img');

```
   image.mapster(
   {
        fillOpacity: 0.4,
        fillColor: "000000",
        strokeColor: "3320FF",
        strokeOpacity: 0.8,
        strokeWidth: 4,
        stroke: true,
        isSelectable: false,
        mapKey: 'name',
        fade: 'true',
        fadeDuration: 750,
        showToolTip: true,
        toolTipClose: ["tooltip-click", "area-click"],
        onMouseover: function(e) {
             $(this).mapster('tooltip');
        }
    });
  });
```

}

What I want to do is that when it hovers above an area, it takes the name attribute of that area (example "7A") and passes that onto a function which will return what the tooltip should display. Is there a way to do that?

**Comment by MB34** [comment]
This possibly?
onMouseover: function(e) {
             $(this).mapster(functionToReturnTooltip(e..options.toolTip[0].name));
        }
