### ISSUE TITLE
Connection with the tag <a>

### ISSUE THREAD

**Issue by PhilippTemkin** [jamietre/ImageMapster#220]
Great plugin! But I'm not good at JS. I would like to implement something like a the map, as avito.ru (for example). When the mouse rolls over to the map - highlighted area on the map and at the same time the link to the right of the map with endemic to the region. and vice versa when you hover over the link - highlighted the link itself and the region on the map. How to implement it using your plugin? I did not find examples of using with tag "a"

**Comment by techfg** [comment]
Hello @PhilippTemkin -

Thank you for your inquiry and apologies for the delayed reply!

I'm not 100% sure I understand what you are trying to achieve but I believe what you would like is that when an area is hovered over, to display something else in a different area of the page.  This can be achieved by using the onMouseover option and when the mouse enters an area, programmatically adjusting the content in the other area of the screen.

Hope this helps!  If you have further general questions about IM, please utilize one of the options described in our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.  If you have encountered an issue with IM or would like to request a feature, please see the information regarding Bug Reports and Feature requests one our [Contributing](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md) page.
