### ISSUE TITLE
ImageMapster on responsive layout?

### ISSUE THREAD

**Issue by Phoenixdown81** [jamietre/ImageMapster#229]
Hi all. I'm designing a responisve website, and I'm using RWD Image Maps (https://github.com/stowball/jQuery-rwdImageMaps)  to create a responsive image map, and it works fine.
I would like to use ImageMapster to add extra effects stroke and fill colors on my image maps, but when I add ImageMapster to my html page, RWD Image Maps doesn't work anymore, so my image map is no longer responsive....  Maybe the 2 scripts are incompatible... 
Any ideas how to make a responsive image map using ImageMapster?

P.S. RWD Image Maps set the image width at 100%, and resize the area of the map proportionally. Adding ImageMapster to the page, the area are not in the correct position (also size is incorrect).

**Comment by Kbam7** [comment]
Hey, i was having the same problem as you. Scrap rwdimagemaps. Use only ImageMapster and have a look as this fiddle. 

http://jsfiddle.net/jamietre/jQG48/

the javascript used here saved me soo much trouble!!

I hope it helps you :)

**Comment by MarkGCarr** [comment]
Hi, I'm very interested in this thread as I'd like to incorporate several image maps in my site and find those created by Imagemapster to be the most appealing. The problem is that I would like(need) to include tooltips in the map, so that when somebody rolls their cursor over the map an information box appears. As well, I would need to know how to target the tool tip so that I can style it with CSS. I've tried using other programs I've found on Code Canyon to for the tooltips, but they don't work with Imagemapster files, there must be a conflict with the coding.

Anyway, if anybody has any information to share it would be very much appreciated. Even a link to where I can find more information would be helpful.

Kind regards,

Mark

**Comment by Phoenixdown81** [comment]
Thank you very much Kbam7!!! :-) This is exactly the solution I need!

**Comment by Kbam7** [comment]
Awesome! :smile: Im glad you managed to sort it out

**Comment by Kbam7** [comment]
MarkGCarr - I have updated the thread at this link - https://github.com/jamietre/ImageMapster/issues/226 - This should give you some assistance with tooltips.

**Comment by Phoenixdown81** [comment]
Hi Kbam7, there is a problem.... I found that bug: if I put an image bigger than the one in the demo, the resize does't work. For example, I put this image in the html: https://dl.dropboxusercontent.com/u/27688106/usa_map_720.png  
It's the same map but the size is 1294 x 800 pixel instead of 720 x 445 pixel of the original map. If you put that url in the html of the fiddle, you'll see that the image map doesn't resize with the image...

Any idea? 

PS. I would like to put a bigger image so in desktop monitor the image is in high resolution. (Sorry if my english is not perfect, but I'm from Italy).

**Comment by Kbam7** [comment]
I was able to get the image to resize. View the screenshots below..
![untitled](https://cloud.githubusercontent.com/assets/12624041/9014448/b4baa032-37c2-11e5-9b97-538f94d6beb4.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/12624041/9014449/b4bd562e-37c2-11e5-928e-a3cc0542b267.jpg)

You can see that the src url is the one you provided. With this bigger image, you will need to define all the areas again though.

**Comment by Phoenixdown81** [comment]
You are right Kbam7! I only need to define all the areas again. Sorry for my stupid question...

**Comment by wkrick** [comment]
I'm using an altImage for mouseover effects and when I use jQuery RWD Image Maps plugin, only the primary image gets resized, the altImage does not.  This messes up the effects.

This solution above always resizes the image map relative to the window size.  If the image map is a smaller part of a larger page, the resizing is wrong.  We need a solution that resizes the image map relative to its parent container, not the window.

**Comment by phillystyle123** [comment]
This is working for me but it's a bit buggy. My image and container div sort of resize but my container div does not stay centered and my image isn't always responsive. [http://cjehost.com/qt/nipt/page6.php](url)

**Comment by techfg** [comment]
Basic auto-resize support as described in #359 was added in #360.
