### ISSUE TITLE
HIGHLIGHTING CUSTOM COLORS FOR IMAGE MAPS COORDINATES

### ISSUE THREAD

**Issue by ghost** [jamietre/ImageMapster#232]
is there a way image map coordinates can be customized with a highlighted color? a good example is when u click on an image map a color pop up box appears then u select or highlight the color of your choice, check out the color picker tool at "http://jscolor.com/try.php"

**Comment by techfg** [comment]
Hello @ghost -

Thank you for your inquiry, apologies for the delayed reply!

IM does not offer a feature for this but you could accomplish by using the [onClick](http://www.outsharked.com/imagemapster/default.aspx?docs.html#onclick) option.  Inside of your handler, you could open a color picker and then based on the user choice, you could use the [set_options](http://www.outsharked.com/imagemapster/default.aspx?docs.html#set_options) API to update the color for the given `mapKey`.

Hope this helps!
