### ISSUE TITLE
Responsive map inside tab is distorted

### ISSUE THREAD

**Issue by Adyyda** [jamietre/ImageMapster#235]
Hello. Please take a look at http://jsfiddle.net/Adyyda/xbxtkkm6/1/

Click on TAB 3 and you will see that the map is distorted and only if we resize the jsfiddle output block the map will become normal. Olso, when the map apears distorted, the hover for states apears tiny, in top left side of the map.

If i place this map outside the tabs, the map will be ok. So, any idea how to make it work as it should? Thanks
![untitled](https://cloud.githubusercontent.com/assets/5921012/9661031/aa0c7e34-520d-11e5-99ff-e4d39d3460f9.png)

**Comment by lalart** [comment]
I modified a little your code and now it works as expected: http://jsfiddle.net/xbxtkkm6/7/

**Comment by Adyyda** [comment]
Thank you. Works ok now.
