### ISSUE TITLE
Bower cannot find ImageMapster

### ISSUE THREAD

**Issue by rupalchawla** [jamietre/ImageMapster#237]
I am unable to download ImageMapster as bower component. I get following error, 
bower ENOTFOUND     Package ImageMapster not found.

**Comment by ndamnjanovic** [comment]
Same here. Did manage to fix it?

**Comment by rupalchawla** [comment]
I added git url in the bower.json. However, I could not restrict against a version number 

dependencies": {
"ImageMapster": "https://github.com/jamietre/ImageMapster.git"
}

**Comment by techfg** [comment]
Releases and tags are now supported as of [v1.2.13](https://github.com/jamietre/ImageMapster/tags).
