### ISSUE TITLE
close button inside tooltip to close tooltip

### ISSUE THREAD

**Issue by sachinlogiciel** [jamietre/ImageMapster#244]
i want to create a close button inside tooltip and click on this close current open tooltip. any idea how to do this??

**Comment by cartond** [comment]
If you add the following to your options, you can use a little trickery
toolTipClose: ["tooltip-click"],
toolTipContainer: '<div> <u>Close</u><br></div>',

This will cause the user to click the tool-tip, which will in turn close it. The word close actually does nothing. Similarly you could put an 'x' and right align it to the div.

http://jsfiddle.net/sb9j7/5812/

**Comment by Gtskk** [comment]
Excellent.

**Comment by sachinlogiciel** [comment]
Thanks u. It works perfectly.
