### ISSUE TITLE
ImageMapster moves an image

### ISSUE THREAD

**Issue by dome68** [jamietre/ImageMapster#250]
I found ImageMapster really useful for my little website but I have a problem.
If I don't use ImageMapster the image is centered on the div (I put margin left and right to "auto" for the image) but if I use ImageMapster the image moves to the left also if I maintain margin left and right to "auto".
Any idea about this weird behaviour of the image?
Thanks for any help.

**Comment by GitGianluc** [comment]
Hi @dome68! Just have a look at [this post] (https://github.com/jamietre/ImageMapster/issues/242#issuecomment-165736107), which actually deals with the same issue.

Hope this helps!

===================================

Ciao @dome68! Dai un'occhiata a [questo post] (https://github.com/jamietre/ImageMapster/issues/242#issuecomment-165736107), che tratta dello stesso problema.

Spero ti sia di aiuto!

**Comment by dome68** [comment]
Grazie mille, Gianluca. Stasera dò un'occhiata più in dettaglio.
(E' quasi strano scrivere in italiano su github).

**Comment by techfg** [comment]
Hello @dome68 -

Thank you for your inquiry, apologies for the delay reply!

@GitGianluc is correct, IM wraps the image with a DIV which will adjust the CSS properties of the image as a result.  However, there isn't an need to modify the IM code itself.  IM exposes two configuration options that you can use: `wrapClass` and `wrapCss`.  See the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html) for more information.

Hope this helps!
