### ISSUE TITLE
Multiple tooltip for the same key

### ISSUE THREAD

**Issue by zido85** [jamietre/ImageMapster#254]
Hello, i am using the version with the zoom on click, i need a tooltip for the key group on hover, and another tooltip for each area after zoom! i can't figure out how to do it :s please any hint?

**Comment by techfg** [comment]
Hello @zido85 - IM now supports tooltip functions which should allow you to accomplish what you are after.  You can define a function for the tooltip that can dynamically determine tooltip content at runtime.  See details in #347.
