### ISSUE TITLE
Trying to implement popup image enlarge. 

### ISSUE THREAD

**Issue by voteleobrown** [jamietre/ImageMapster#256]
Basically I have a large image that has thumbnails embedded in parts of itself. I want popups to occur when various regions of the image maps are clicked, and was planning to use Highslide alongside Imagemapster to do this but can not figure out the best way to do it. 

A more detailed description of the problem is posted here:
http://stackoverflow.com/questions/36855190/trying-to-integrate-a-popup-using-highslide-into-an-image-mapped-with-imagemapst

Is there an easy way to do this natively within Imagemapster that can be made to have an appearance that fits with a webpage aesthetically? Or a good way to follow through on my original desire to use Highslide for this? 

Highslide, in case you aren't familiar, is this:
http://highslide.com/

Thanks.

**Comment by techfg** [comment]
Hello @voteleobrown -

Thanks for your question, apologies for the delayed reply.

If I'm understanding correctly, you would like to a popup to open when the user clicks an area on the imagemap.  This can be achieved by using the IM [onClick](http://www.outsharked.com/imagemapster/default.aspx?docs.html#onclick) option.  In short, when an area is clicked, you're even handler will display the popup using highslide.

The challenge that you are having with the code you posted in SO is that you are trying to use the `href` attribute of the area to trigger an onclick which is not valid HTML and will not work either with IM or even without IM.  Also, your `img` element is inside your `map` element which is invalid HTML.

Your IM init should look something like the following:

```js
$('#leoweb').mapster({
    singleSelect : true,
    render_highlight : { altImage : 'img/open.jpg' },
    mapKey: 'hex',
    fill : true, altImage : 'img/open.jpg',
    fillOpacity : 1,
   onClick: function (data) {
      // open highslide conditionally based on data.key
   },
  clickNavigate: false
});
```

and your HTML should look similar to the following:

```html
<img src="img/hex1.png"  alt="" style="width: 107px;height:120px;" />
<map name="leoweb" id="leoweb">
    <area hex="1" href="#" shape="poly" coords=" 463,73, 363,74, 305,160, 363,258, 462,255, 513,168, 465,76" />
    <area hex="2" href="#" shape="poly" coords=" 579,196, 521,292, 578,384, 675,388, 733,294, 683,200, 585,198" />
    <area hex="3" href="#" shape="poly" coords=" 243,202, 138,202, 86,293, 133,379, 245,382, 295,293, 251,206, 245,206" />
   ....
</map>
```

Hope this helps!  If not, please refer to our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for options on how to obtain general assistance with IM.
