### ISSUE TITLE
staticState behavior

### ISSUE THREAD

**Issue by franckblais** [jamietre/ImageMapster#257]
Hello,

First, thanks for the library: it's awesome, and colleagues as well as customers sees it.

I am posting because I am currently developing an application with Mapster, and I really require those functionalities:
- All areas are displayed by default
- Areas can be selected
- To have specific properties when selected (basically render_select but not applied when staticState is on)

Now, my issue concerns staticState: it's exactly what I am looking for except: when on, all areas are considered selected, therefore "render_select" properties applies and a user cannot know which area he tried to select ...

For dashboarding, it's pretty mandatory to see all areas. Else, you would have to move your mouse on the image to see "Oh, an area here ... !", especially when I colored them dynamically depending on measures ...

I base my application on a beta, before you reworked the library, and kinda managed to make it work as I want by tweaking it a bit (you can check it here with tabs FBL: https://github.com/org-scn-design-studio-community/sdkpackage/blob/master/src/org.scn.community.databound/os/jquery.imagemapster/jquery.imagemapster.js )

I still have an issue, but not blocking: areas stack together when both displayed and selected, resulting with a color mix when opacity is < 1.

I tried to replicate it on the new version, but couldn't. Your build is a bit too complicated for me ...
Could you help me implementing this behavior ? Guide me ? Or just tell me if it could be achieved on the latest version ?

I'll try again, but last time I checked, the staticState was not even working (all areas disappeared ...)

Thanks for reading and giving some help :)

**Comment by franckblais** [comment]
Hi,

Actually, my version was really on the last one. While testing and updating, I may have selected a wrong version.

The remaining issues are on the overlapping areas when static is activated and an area is highlighted / selected.

**Comment by lucaspanik** [comment]
I need displayed areas by default with possibility the select.

It is possible?

Thanks

**Comment by franckblais** [comment]
Hello Lucas,

I have modified my local copy of the library to do that. I could give you the code if you want. I was long to develop but working at the end.
Have a look at my mapster library here and look for FBL inside, you'll see where I have updated the code.
https://github.com/org-scn-design-studio-community/sdkpackage/blob/master/src/org.scn.community.databound/os/jquery.imagemapster/jquery.imagemapster.js

**Comment by techfg** [comment]
Hello @franckblais -

Thank you for your inquiry, apologies for the delayed reply!

I've taken a look at your code and kind of understand what you are trying to achieve but not 100%.  If you could provide more specifics on what IM currently does and how you would want that to change and include a [jsFiddle](https://jsfilddle.net) that achieves the outcome using your modified version, happy to evaluate this further and see if it makes sense to incorporate in to core IM features.

**Comment by techfg** [comment]
Hello @franckblais -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
