### ISSUE TITLE
On hover don't show fill color

### ISSUE THREAD

**Issue by pauliusvitkus** [jamietre/ImageMapster#259]
Hello everyone,

First of all, thanks for great tool. Use it a lot.

Usually I don't have problems with ImageMapster, but this time it works only in one place - when you hover on specific real estate objects or floors of object ([LINK](http://pilaitesterasos.excellence.lt/#paieska)). When you click on whatever floor of Namas D, you get floor and there should be filled collors initially, but that's not working.

There is code:

```
jQuery('#daugiabutisAukstas1').mapster({
     fillOpacity: 0.5,
     fillColor: "adcd83",
     stroke: true,
     strokeColor: "000000",
     strokeOpacity: 0,
     strokeWidth: 2,
     singleSelect: true,
     scaleMap: true,
     mapKey: 'name',
     listKey: 'name',
     showToolTip: false,
     toolTipClose: ["tooltip-click", "area-click"],
     areas: [
         {
             key: "daugiabucioAukstas1Butas1",
             fillColor: "d42e16",
             staticState: true
         },
         {
             key: "daugiabucioAukstas1Butas20",
             fillColor: "d42e16",
             staticState: true
         },
         {
             key: "daugiabucioAukstas1Butas21",
             fillColor: "d42e16",
             staticState: true
         }
         ]
  });
```

Could anyone help me, please?

**Comment by jornklung** [comment]
Have you tried:
`         {
             key: "daugiabucioAukstas1Butas1",
             fillColor: "d42e16",
             staticState: true,
             selected:true
         }`

**Comment by jornklung** [comment]
If you need highlight of areas, then you need to define that with render_highlight: { props }
