### ISSUE TITLE
Highlight all areas all the time

### ISSUE THREAD

**Issue by kromalski** [jamietre/ImageMapster#266]
Is it possible to highlight all areas on start and keep them highlighted even when hovered/unhovered?
Right now I can set highlights on start but they disappear when hovered and unhovered again.
I want to keep them highlighted and only change fill color on selection.

Thanks in advance.

**Comment by techfg** [comment]
Hello @kromalski -

Thank you for your inquiry, apologies for the delayed reply!

If I'm understanding your question correctly, the [staticState](http://www.outsharked.com/imagemapster/default.aspx?docs.html#staticstate) option should be able to provide you what you are looking for.

If this doesn't help, please refer to our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for options on the best ways to receive help on general IM support questions.
