### ISSUE TITLE
Using imagemapster with bootstrap. Both working but image with usemap not responsive

### ISSUE THREAD

**Issue by phillystyle123** [jamietre/ImageMapster#271]
Using imagemapster with bootstrap. Both working but image with usemap not responsive.  Check out my page here: [http://cjehost.com/qt/nipt/page6.php](url). Notice, when the browser is reloaded the imagemap image will resize but when you drag the browser window larger/smaller, the imagemap image does not resize.

**Comment by garrett-eclipse** [comment]
@phillystyle123 This workaround I used for the WP Plugin should function without Wordpress as it's just jquery;
https://wordpress.org/support/topic/solution-make-imagemapper-responsive/

**Comment by garrett-eclipse** [comment]
*I realize comparing the WP Plugin with the jQuery script that the Plugin wraps the image in a div with class 'imgmap-frontend-image' which I use in my snippet. So just wrap your image map in a div or change which container it uses to get the width

**Comment by techfg** [comment]
Basic auto-resize support as described in #359 was added in #360.
