### ISSUE TITLE
Add the package to NPM

### ISSUE THREAD

**Issue by MonsieurV** [jamietre/ImageMapster#273]
Hey here!

In the vein as #165, it would be super nice to have the package distributed through NPM.

Links on how to do that:
* https://docs.npmjs.com/getting-started/publishing-npm-packages
* https://gist.github.com/coolaj86/1318304

(May take up to 10-15 minutes the first time, then just a one-shot `npm publish` is fine enough)

I can do a PR for that :)

Great plugin, thanks for your work! 👍

**Comment by jamietre** [comment]
If you want to refactor this to be distributable via NPM that would be great - I just don't use it at all any more and have very little spare time.

The current code distributes a customized version of an old promise library called when.js. This should also be removed. There is no reason not to depend on a global Promise object at this point in time. This probably requires some minor refactoring. IIRC this has something to do with the problem in using imagemaster with bundlers or as a commonjs module.

**Comment by davidnewcomb** [comment]
@jamietre, did you do the refactoring because 1.2.10 is currently on NPM?!
Release notes say the current released version is 1.2.13.
Any chance you could bump it up to the latest version?

**Comment by techfg** [comment]
@davidnewcomb - The [jquery-imagemapster](https://www.npmjs.com/package/jquery-imagemapster) package that you saw on NPM wasn't an officially published package and didn't support UMD.  The official [imagemapster NPM package](https://www.npmjs.com/package/imagemapster) is now available and includes full UMD support.
