### ISSUE TITLE
Using the Mapster resize option on Window resize make the script responsive

### ISSUE THREAD

**Issue by garretthyder** [jamietre/ImageMapster#275]
Hello,

Wanted to share a jQuery snippet which would make the plugin responsive;
```
// Responsive ImageMapper - Resize Mapster on Window Resize
jQuery(document).ready(function($) {
    if ($('img[usemap]').length) {
        $(window).resize( function() {
            $('img[usemap]').each(function() {
                $(this).mapster('resize',$(this).closest('.imgmap-frontend-image').width());
            });
        });
    }
});
```
Source: https://wordpress.org/support/topic/solution-make-imagemapper-responsive/

Cheers

**Comment by garrett-eclipse** [comment]
*I realize comparing the WP Plugin with the jQuery script that the Plugin wraps the image in a div with class 'imgmap-frontend-image' which I use in my snippet. So just wrap your image map in a div or use container size.

**Comment by techfg** [comment]
Hello @garretthyder -

Thanks for sharing this with the community!  As of v1.5.0, ImageMapster has a built in basic autoresize/responsive feature.  See #359 for details.

**Comment by garretthyder** [comment]
That's great news @techfg, thank you.
