### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by clairetsai818** [jamietre/ImageMapster#276]
Hi! I am a member of [CDNJS](https://github.com/cdnjs/cdnjs).
We'd like to add this lib to our CDN, and the git auto-update relies on git tags so that it can recognize the correct version and automatically update the repo. Could you please add tags to this repo?
Thank you!

https://github.com/cdnjs/cdnjs/issues/10627

**Comment by techfg** [comment]
Hello @clairetsai818 - Releases and tags are now supported as of [v1.2.13](https://github.com/jamietre/ImageMapster/tags), thank you!

https://github.com/cdnjs/cdnjs/issues/10627
