### ISSUE TITLE
Opening image in popup the second time

### ISSUE THREAD

**Issue by elgurinn** [jamietre/ImageMapster#290]
I open a popup that contains the image that ImageMapster points at, when I close the popup and open another one. The highlight does not work, put I can click the image (select works). 

This is the error message I get.

`core.es5.js:1020 ERROR TypeError: Cannot read property '0' of null
    at u.MapData.getAllDataForArea (scripts.bundle.js:21)
    at HTMLAreaElement.r (scripts.bundle.js:21)
    at HTMLAreaElement.n.mouseover (scripts.bundle.js:21)
    at HTMLAreaElement.dispatch (scripts.bundle.js:4)
    at HTMLAreaElement.q.handle (scripts.bundle.js:4)`

Anyone that has encountered the same error as I and can help me out?

**Comment by techfg** [comment]
Hello @elgurinn -

Thank you for bringing this to our attention, apologies for the long delay in reply!

Given your use case, I'm fairly certain that the issue you encountered is identical to #313 which was resolved in #315.

Please upgrade to the latest version and if the problem persists, please let us know and provide a full repro per our [Bug Report](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
