### ISSUE TITLE
Using TypeScript in VS2017

### ISSUE THREAD

**Issue by ClaudeVernier** [jamietre/ImageMapster#297]
Hello, 

I started a new HTML5 project some time ago to learn TypeScript and I couldn't get it to work so I stopped and now I am back at it !
Well, the project works but when I call the mapster constructor, it says undefined.

In my HTML page, I have this:
     <script src="scripts/jsquery-3.2.1.js"></script>
     <script src="scripts/jsqueryimagemapster.js"></script>

I can't recall how I installed imagemapster but there is local JS file with this header: 
    /* ImageMapster Version: 1.2.10 (2/25/2013)

I did install the TypeScript file from NuGet: 
      imagemapster.TypeScript.DefinitelyTyped v0.0.1

In my main TS file I have: 
   /// <reference path="../typings/jquery/jquery.d.ts" />
   /// <reference path="../typings/imagemapster/imagemapster.d.ts" />

In code, when I click on an image, I want a DIV to be shown with an image and an map over it so:
   onImageClick(MouseEventArgs: any) {

     let mapsterOpts: ImageMapster.Options = {
          singleSelect: true,
          fill: true,
          onClick: function(e) { console.log(e); },
          onMouseOver: function(e) { console.log(e); },
     }

    let myObj: any = $("#img").mapster(mapsterOpts);

/* code never gets here*/
    myObj.mapster('set', true);
}

I have searched for sample or JsFiddle using TypeScript and ImageMapster but with no luck, build works, it only fails at runtime.

Hoping you will be able to help me, thank you very much.

Claude VERNIER

**Comment by techfg** [comment]
Hello @ClaudeVernier -

The TS definitions that you mention are from a different source although based on the error message you indicated, it wouldn't appear that TS has anything to do with the problem.

The fact that the constructor is not defined likely means that imagemapster is not being loaded correctly, although without full view of your source code, it's difficult to say.

You mention you have imagemapster locally and the header indicates v1.2.10.  That version is very old but even still, it should work for what you are trying to do.

Possibly the version you have locally isn't a "clean" copy of the official v1.2.10 release of imagemapster.

Can you please try changing the script tag for imagemapster:

<script src="https://cdn.jsdelivr.net/npm/imagemapster/dist/jquery.imagemapster.min.js"></script>

If the problem persists, please provide a full repro via jsFiddle and we'll be happy to take another look.

**Comment by ClaudeVernier** [comment]
Hello !
Thanks for coming back to me !  

I manage to work on that project about 3 months per year !!!

Right now, it still uses TypeScript and ImageMapster, can't remember how but I was able to overcome the above issue.

Still, thanks a lot, I'll try to update to latest release at some point, I noticed that on mobile devices, I wanted ImageMapster to behave a bit differently so maybe latest version will help !!

Best regards, 
Claude

**Comment by techfg** [comment]
@ClaudeVernier - Glad you were able to work past the issue, thanks for the update!
