### ISSUE TITLE
Docs unavailable

### ISSUE THREAD

**Issue by lclghst** [jamietre/ImageMapster#300]
Currently the docs are unavailable (looks like domain has expired)
In the meantime you can use the wayback machine to view previous captures.

https://web.archive.org/web/20180421021238/http://www.outsharked.com/imagemapster/default.aspx?docs.html

**Comment by jamietre** [comment]
Thanks - my registrar pulled a fast one but I got it back, should be available again soon.

**Comment by lclghst** [comment]
Hey no worries. Registrars can be pretty shady, in my experience.

**Comment by jamietre** [comment]
Seems to be alive again!
