### ISSUE TITLE
[FIXED] jsdelivr is active!

### ISSUE THREAD

**Issue by j2l** [jamietre/ImageMapster#305]
Simply use this when you build it and it will works (for 2019 at least).
```
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>

<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/jamietre/ImageMapster/dist/jquery.imagemapster.min.js"></script>
```

**Comment by techfg** [comment]
Releases are tagged as of 1.2.13 and are now available via jsdeliver for version 1.3.1+

Lastest Release - [https://cdn.jsdelivr.net/npm/imagemapster/dist/jquery.imagemapster.min.js](https://cdn.jsdelivr.net/npm/imagemapster/dist/jquery.imagemapster.min.js)

Version 1.3.1 - [https://cdn.jsdelivr.net/npm/imagemapster@1.3.1/dist/jquery.imagemapster.min.js](https://cdn.jsdelivr.net/npm/imagemapster@1.3.1/dist/jquery.imagemapster.min.js)
