### ISSUE TITLE
how to color and discolor an area with imagemapster?

### ISSUE THREAD

**Issue by ssenn4** [jamietre/ImageMapster#310]
I've been having this problem for about a week and I don't know how to solve it, I've been looking for many tutorials but I couldn't solve it, can someone help me?

https://stackoverflow.com/questions/64753444/how-to-color-and-discolor-an-area-with-imagemapster

**Comment by techfg** [comment]
Hello @ssenn4  - The link you referenced no longer exists.  If you are still have questions or are having problems, please open a new issue and provide the details with an example so that we may try to assist.  ty!
