### ISSUE TITLE
Migrate website to github

### ISSUE THREAD

**Issue by techfg** [jamietre/ImageMapster#322]
ImageMapster website is currently hosted at http://www.outsharked.com/imagemapster and its [creator](@jamietre) has graciously covered the hosting costs along with maintaining it throughout the years (thank you @jamietre!).  

Beyond the hard costs, keeping the site updated, etc. is challenging as it requires him to get involved directly instead of being community supported.

Would be great to see someone take on the effort of migrating the existing site to github either within the wiki, GitHub Pages, etc.  Key elements of this would be updated documentation and ability to view examples, etc.

Any takers?

**Comment by Itsaadarsh** [comment]
Hello there @techfg , I'd love to do this task. So basically you want to switch your hosting service to **GitHub Pages**, where all the HTML docs pages render using GitHub Pages, is that right? Or do you want to change the whole UI of your documentation?

**Comment by techfg** [comment]
Hello @Itsaadarsh -

This is awesome, thank you for your interesting in taking this on, greatly appreciated!

Regarding my thoughts on what this should involve, the primary goal is to take the relevant "information" (demos, faq, docs, etc.) at the current site and create a new site hosted on github, likely on GitHub Pages but open to ideas on how best to do this.  

The key is that as much (hopefully all) of the information gets migrated but the design doesn't have to - in fact, would be great to modernize the UI/UX with the new site.  Again, completely open to ideas on how best to accomplish this.

Does that answer your question(s)?

**Comment by jamietre** [comment]
@techfg Thanks so much for breathing life back into this project and I'm sorry I haven't had much time to be involved. But it seems like it's in very good hands! I'm paying attention mostly as a fly on the wall, but feel free to email me directly if there's something you need from me that I'm really holding you up on. This is exciting and I will try to get more involved as time permits!

Thanks in advance to the effort to migrate the web site. I can provide the source code to the existing site (I think... it's been years since I touched it...) if that will be helpful; it's mostly client side javascript with an ASP.NET/C# backend that does only a few things iirc like query github for the most recent version to display dynamically, which probably isn't working any mor anyway.

**Comment by techfg** [comment]
@jamietre - Happy to help and thanks again for all your efforts in making ImageMapster what it is today!  Sounds great about the source code, @Itsaadarsh, would that be helpful for you?

**Comment by Itsaadarsh** [comment]
Well, tbh I'm not really good at changing UI\UX or writing HTML and CSS from scratch, so I'll help you guys in migrating your existing documentation to GitHub pages. So once I see the main documentation codebase I'll start working on the migration.
Sounds good?

**Comment by techfg** [comment]
@Itsaadarsh - Sounds like a plan, we can evolve the implementation as you get things started and possibly some others can contribute as well.  Thanks again for your willingness to help!

**Comment by Itsaadarsh** [comment]
Okay! Where do I find the documentation repo, the one with all the HTML pages?

**Comment by techfg** [comment]
@Itsaadarsh - @jamietre mentioned he's going to dig it up and send our way.  Worst case, If he's unable to locate, you'll just have to replicate the content which hopefully shouldn't be too difficult :)

**Comment by jamietre** [comment]
I found the source code; I'll make a git repo. I just need to go through it to sanitize it since it's never been open sourced before

**Comment by techfg** [comment]
@jamietre - I've never used GH Pages before but from some quick reading, it looks like you can enable GH pages in this repo via Settings and just target a branch to contain the pages.  Possibly it makes sense to create a branch called "old-website" for the current website code (or just put in a separate repo) and then go through the GH Pages setup wizard picking a theme you like and targeting a branch in this repo called 'gh-pages'?

**Comment by jamietre** [comment]
@techfg sounds simple enough. I'll push all the code in another branch. I should have some time today to get that up there.

**Comment by Itsaadarsh** [comment]
@techfg Ya sure create a new branch and push all the old website source code in that and don't name the branch `gh-pages`, as there will be conflicts while deploying on Github pages.

Just to be clear you're gonna push the old source code onto this repo right?

**Comment by techfg** [comment]
@Itsaadarsh - I believe @jamietre is indicating that he'll push the existing website code in to a branch in this repo (e.g. branch: old-website).  Additionally, I believe he is the only one that can enable GH pages within this repo (via the Settings tab) so he can go through the GH Pages setup wizard, pick a theme and create a branch that will contain the GH Pages (e.g. branch: gh-pages).  Will that work?

**Comment by jamietre** [comment]
I just pushed `website-archived`. I can do the GH pages setup whenever you want, just let me know what branch to point it to. (I've never done it before so just assuming your instructions here are correct).

**Comment by techfg** [comment]
@jamietre - Awesome, ty!  I've never used GH pages either so will be learning experience for both of us.  From what I've seen/read, most repos that have GH Pages enabled use a dedicated branch (nothing else except the site itself in that branch) and of the ones I've looked at, `gh-pages` is the most common branch name.  I'll defer to @Itsaadarsh for guidance as this is all new to me :)

**Comment by Itsaadarsh** [comment]
Hey guys, so I just went through the whole website codebase and noticed that the tech stack used is C#, but the problem is that I'm not really familiar with C# code base. But I'll try and understand the codebase in the coming days and try to contribute as much as possible.

**Comment by jamietre** [comment]
You should be able to ignore most of it, honestly. I am 99% sure the routing *within* the ImageMapster section itself is all client side (or maybe it did have server side routing if you hit it with a direct URL or something? but should work client only). It seems to behave like that too, just playing around real quick.

I don't remember the first thing about the actual templating of the HTML, but you could always just download the raw HTML from the site as it is rendered to day and use that as a starting point if we are using some kind of server-side templating for the site structure.

There was one piece that did a query against github to get the latest version automatically. But most of it, I think, should be extractable from the infrastructure without a lot of trouble.

**Comment by techfg** [comment]
Agree with @jamietre, I think the "key" here is to replicate the content not the code.  The look & feel of the new site can and should be completely different and can be based on the chosen GH Pages theme. 

@Itsaadarsh - Possibly a good first step is to create the initial shell site, setup nav, etc. and then implement the [docs page](http://www.outsharked.com/imagemapster/default.aspx?docs.html) focused on its content.  From there, you can tackle additional pages (e.g. examples), etc. but this will give a good starting point and get something up and running.  Thoughts?

@jamietre - Couple of q's:
1. Can you configure GH Pages via settings in the repo and target a branch called `gh-pages`.  From there, @Itsaadarsh can create a fork and start working on things.
2. Sent you an email with a question about one area of code that I couldn't quite figure out, would appreciate your thoughts when you have a chance to review

Thanks guys!
