### ISSUE TITLE
Feature: onTooltipClose event

### ISSUE THREAD

**Issue by jamietre** [jamietre/ImageMapster#33]
Add an event when a tooltip is dismissed to match the creation event, this is difficult to obtain from a client.

**Comment by techfg** [comment]
The onHideToolTip option was added in this [commit](https://github.com/jamietre/ImageMapster/commit/4d4068e865cc3046ce71f11f49a4c41325b47214#diff-5c0c78da9a36e43b00b856d7477f55b868ec23fe0aef8ae47836a71a02d957c7).

Closing.
