### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by techfg** [jamietre/ImageMapster#372]
Per https://github.com/github/renaming, rename default branch to `main`.

@jamietre - Only the owner can edit the name, can you update and then merge #373 when you get a chance please?  Ty!

**Comment by jamietre** [comment]
Ah crap. Sorry I wasn't paying attention, I thought you just wanted my signoff on this. Let me see if I can fix it now..

**Comment by techfg** [comment]
@jamietre  - No worries, thanks for making the change, all looking good now :)
