### ISSUE TITLE
[TouchScreen only] Weird highlight glitch when touch on the other area beside the map.

### ISSUE THREAD

**Issue by Chheung** [jamietre/ImageMapster#394]
**Describe the bug**
The map seems to be have hovering effect when a touchscreen device ( can be done on chrome dev tool ) clicks on anywhere on the webpage.

**To Reproduce**

1. Open chrome . Fiddle: https://jsfiddle.net/new68oy4/3/
2. Toggle Device Mode
3. Click on anywhere in the webpage ( aside from the map ) and it will show hovering effect on the last items of the map. 

**Expected behavior**
Not show this effect glitch for touchscreen.

**Screenshots**
For video (loom): https://www.loom.com/share/78a2610cc50b4cd184b86f463065895a

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Browser Chrome
- Version 12.1

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro Max
- OS: iOS 15.1
- Browser Safari
- Version 15.1

**Comment by Chheung** [comment]
A temporary workaround I found is to add another area (make sure it is the last one) which has coords: '0,0' ....

**Comment by wangshuihua** [comment]
I have the exactly same issue, but it cannot be solved by adding an extra area of coords="0,0".

**Comment by wangshuihua** [comment]
> I have the exactly same issue, but it cannot be solved by adding an extra area of coords="0,0".

My temporary workaround is to add "highlight: null" option for mobile browser, then area highlight should be OK, but the last tooltip still has the same issue.

**Comment by iliaparvanov** [comment]
Any findings on this issue? Neither of the aforementioned workarounds work for me since highlight: null disables the highlighting on desktop browsers and not only on mobile browsers.

**Comment by techfg** [comment]
@Chheung - Thank you for reporting this issue.  It has been resolved in [v1.6.0](https://github.com/jamietre/ImageMapster/releases/tag/v1.6.0) which was just released.
