### ISSUE TITLE
Export image

### ISSUE THREAD

**Issue by WhoAndWhy** [jamietre/ImageMapster#402]
Hi,
I use  versione 1.2.10. 
Having the need to export the image with the areas to db, I created this implementation which I share with you as an idea to use in the current version (if not already done)

this is the implementation
me.toDataUrl = function () {
    return (new m.Method(this,
        function () {
            var canvas = this.graphics.createVisibleCanvas(this);
            var context = canvas.getContext('2d');
            context.drawImage(this.image, 0, 0);
            context.drawImage(this.base_canvas, 0, 0);
            return canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
        },
        null,
        { name: 'toDataUrl' }
    )).go();
};

Hope can be useful

**Comment by techfg** [comment]
Hello @WhoAndWhy  -

Thank you for your contribution.  I'm going to close this issue as it doesn't require anything further but if you'd like to submit a PR to officially add this functionality,  we'd be happy to consider it.
