### ISSUE TITLE
Forgotten console.log in v1.7.0

### ISSUE THREAD

**Issue by darksabrefr** [jamietre/ImageMapster#420]
### Describe the bug

Hello,
There's a forgotten console.log in the brand new version 1.7.0 at this place : https://github.com/jamietre/ImageMapster/blob/main/dist/jquery.imagemapster.mjs#L1185

Have a good day !

### Reproduction

Everywhere

### Steps to reproduce

Simply load the lib and check in your console

### Environment Info

All

### Expected Behavior

No console.log !

**Comment by techfg** [comment]
Thanks @darksabrefr!  Already noticed that, working on an updated release that removes it along with another bug I just found :)  Should be released soon!
