### ISSUE TITLE
[✨] Areas not affected by resize when difference <= 2%

### ISSUE THREAD

**Issue by siemova** [jamietre/ImageMapster#424]
### Describe the bug

When using the `resize` API, map areas are not affected unless the size difference exceeds 2%.

### Reproduction

https://codepen.io/siemova/pen/raByRER

### Steps to reproduce

1. Embed an image which uses a map containing an area.
2. Apply ImageMapster to the image.
3. Use ImageMapster's `resize` API to set a width <= 2% different.
4. Observe that the image is resized but the map area is not.

### Environment Info

Any

### Expected Behavior

Map areas should always be resized to maintain alignment with the image.

### Additional Information

This is a long-standing issue originally reported via https://github.com/jamietre/ImageMapster/issues/269.

The problem is caused by [these lines](https://github.com/jamietre/ImageMapster/blob/e11142562f767f393ecf23cd0cfee8100626696a/src/scale.js#L22-L24) in the library code.

**Comment by techfg** [comment]
@siemova - 

Thanks for opening and providing the details and easy to reproduce example 😄 There is a comment in the code from back in 2011 about avoiding float errors and hence why this situation exists.  Unfortunately, I'm not seeing any tests around this nor any additional information about what scenarios this code is intended to avoid.  I'll try to find some time to take a look and see where/how allowing full range of resize caused an issue and see if I can come up with a fix.  

Thanks again!

**Comment by techfg** [comment]
@siemova -

Thank you again for creating the repro.  A new configuration option has been added in v1.8.1 to enable support for controlling if and how ImageMapster restricts area map coords during a resize.

See [scaleMapBounds](https://jamietre.github.io/ImageMapster/reference/configuration-reference/#scalemapbounds).
