### ISSUE TITLE
Highlighting fn is not working in android device....

### ISSUE THREAD

**Issue by rishiphp** [jamietre/ImageMapster#80]
Hi,

I'm dynamically highlighting the area using hightlight fn, like

$("#AREA_ID").mapster('highlight', true); and $("#AREA_ID").mapster('highlight', false);

also tried with calling fn like this way,    $('img').mapster('highlight',"key");

Its works fine in mapster v1.2.4,  but it not working in 1.2.5 and 1.2.6...

Note: the latest version works fine in browser.. not working in android device.

**Comment by techfg** [comment]
Hello @rishiphp -

Thank you for reporting this and apologies for the delayed reply.

It's difficult to say whether or not there was an underlying issue with 1.2.5/1.2.6 or not but I can confirm that highlighting works via the API in the latest version (currently v1.5.1).

A couple of notes:
1) When using an AREA as a selector, there is no second parameter - calling 'highlight' on an area will always 'highlight' it. To remove the highlight, you must call highlight on the image passing in false.
2) in your code `$('img').mapster('highlight', 'key')`, this will select all `img` tags on the page including `img` elements that imagemapster creates internally.  It's always best to, at a minimum, use the selector `$(img[usemap])` or better yet, add classes or ids to your images and use those as selectors to ensure you are only calling mapster methods on elements you've initialized mapster with.


Please see [fiddle](https://jsfiddle.net/techfg/aqt67xLh/17/) and try the following:

```js
$('#john').mapster('highlight', true)
$('#beatles').mapster('highlight', 'ringo')
$('#beatles').mapster('highlight', false)
```

Hope this helps!
