### ISSUE TITLE
iPad issues

### ISSUE THREAD

**Issue by philjones88** [jamietre/ImageMapster#84]
Hi,

Having issues with ImageMapster and iPad.
1. The fill doesn't work
2. Navigation required two taps/clicks

I have had the two taps/clicks issue elsewhere. It is due to showing elements on mouse over.

http://www.nczonline.net/blog/2012/07/05/ios-has-a-hover-problem/
http://blog.0100.tv/2010/05/fixing-the-hover-event-on-the-ipadiphoneipod/

If you don't have an iPad for testing, just use http://www.browserstack.com as they provide simulators and give 30 minutes free time (maximise your free time, by starting and stopping when working on changes).

The actual page (this link will die as soon as it goes link);

http://mtv.mangomint.com/orte

(There are probably other bugs too, just staging environment atm)

Thanks for any help you can provide!

**Comment by techfg** [comment]
It appears that the original issue described by @philjones88 was resolved per his comments.

@abhi020585 - IM should work properly on iPad although, earlier versions did have some issues as you saw with @philjones88 & @jamietre discussion.  Unfortunately, you only indicate "fails on iPad" so without more context its difficult to say what your issue could have been.  If you are still seeking a solution, please try the latest version of IM and if you continue to have problems and believe that you have found a possible bug, please create a new issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
