### ISSUE TITLE
Show tooltip on click

### ISSUE THREAD

**Issue by ghost** [jamietre/ImageMapster#91]
Hi, thanks for the plugin, it's great.

Is it possible to have the tooltip appear onclick instead of mouseover? The reason I ask is that I've implemented Mapster into a responsive site, and when the viewport gets to mobile sizes, i've coded it to switch over to tooltips instead of writing the data to a div. 

The problem is that I need to bind the tooltip to a tap or click event to make it work on a touch screen. Any advice?

Many thanks.

**Comment by duy-tran** [comment]
Somehow 

onMouseover: function(e) {
             $(this).mapster('tooltip');
        }

doesn't work for me, the tooltip is still showed up on hovering
My options:
        scaleMap: true, 
	render_highlight : { fillColor: 'ff2f2f' },
        mapKey: 'title',
	fill : true,
	fillColor : 'ff0000',
	fillOpacity : 0.8,
	stroke : true,
	strokeColor : 'ff0000',
	strokeWidth : 2,
	singleSelect: true,
	isSelectable: false,
        listKey: 'title',
        onClick: function(e) { 
    	        $(this).mapster('tooltip');
   	},
	showToolTip: true,
	toolTipClose: ["area-click","tooltip-click"],
	toolTipContainer: '<div class="toolTip"></div>',
        areas: [....]

**Comment by maurohead** [comment]
Someone can I resolve this?
